const ADD_DEVELOPERS = "ADD_DEVELOPERS";
const EDIT_DEVELOPERS = "EDIT_DEVELOPERS";
const LIST_DEVELOPERS = "LIST_DEVELOPERS";

const GET_DEVELOPER = "GET_DEVELOPER";
const DELETE_DEVELOPER = "DELETE_DEVELOPER";

export { ADD_DEVELOPERS, EDIT_DEVELOPERS, LIST_DEVELOPERS, GET_DEVELOPER, DELETE_DEVELOPER };
