const ADD_DEVELOPER = "ADD_DEVELOPER";
const EDIT_DEVELOPER = "EDIT_DEVELOPER";
const LIST_DEVELOPERS = "LIST_DEVELOPERS";
const DELETE_DEVELOPER = "DELETE_DEVELOPER";

export { ADD_DEVELOPER, EDIT_DEVELOPER, LIST_DEVELOPERS, DELETE_DEVELOPER };
